services:
  
  db:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=cinema_db
    ports:
      - '5433:5432'
    volumes: 
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
